---
# tasks file for docker
- name: "install docker part 1"
  become: yes
  package:
    pkg: 
      - ca-certificates 
      - curl 
      - gnupg
    state: present

- name: install docker key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker repo
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "install docker part 4"
  become: yes
  package:
    pkg: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
    update_cache: yes
    state: present